#!/usr/bin/env bash

trunkroot="$(dirname $(dirname $(realpath $0)))"

# install packages
apt-get update &&
  # requirements
  apt-get install -y git curl &&
  # complements
  apt-get install -y ripgrep

# install bat
BAT_VERSION="0.22.1"
curl --output-dir /tmp -LO "https://github.com/sharkdp/bat/releases/download/v${BAT_VERSION}/bat_${BAT_VERSION}_amd64.deb" &&
  dpkg -i "/tmp/bat_${BAT_VERSION}_amd64.deb" &&
  git clone --depth=1 "https://github.com/eth-p/bat-extras.git" /opt/bat-extras &&
  /opt/bat-extras/build.sh --install

cd "$trunkroot"

rcpath="${HOME}/.shellrc.d"

mkdir -p "$rcpath" &&
  cp scripts/shellrc.d/20-bat.sh "$rcpath"
