#!/usr/bin/env bash

trunkroot=$(dirname $(dirname $(realpath "$0")))

cleanupdotd="$trunkroot/cleanup.d"

if [ -d "$cleanupdotd" ]; then
  for script in $cleanupdotd/*; do
    source $script
  done
fi

apt-get -y autoremove &&
  apt-get clean &&
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* "$trunkroot"
